FROM node:alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./apps/web ./apps/web
RUN npm i -g pnpm
RUN pnpm install

CMD ["npm","run","start:web"]